import unittest
from exceptions import PaymentException
from user import User


class MiniVenmo:
    def create_user(self, username, balance, credit_card_number):
        user = User(username)
        user.add_to_balance(balance)
        user.add_credit_card(credit_card_number)
        return user

    def render_feed(self, feed):
        for entry in feed:
            print(entry)

    @classmethod
    def run(cls):
        venmo = cls()

        bobby = venmo.create_user("Bobby", 5.00, "4111111111111111")
        carol = venmo.create_user("Carol", 10.00, "4242424242424242")

        try:
            # should complete using balance
            bobby.pay(carol, 5.00, "Coffee")

            # should complete using card
            carol.pay(bobby, 15.00, "Lunch")
        except PaymentException as e:
            print(e)

        bobby.add_friend(carol)
        venmo.render_feed(bobby.retrieve_feed())
        venmo.render_feed(carol.retrieve_feed())


if __name__ == "__main__":
    MiniVenmo.run()
